# Generated by Django 3.1.4 on 2022-11-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='countInStoc',
        ),
    ]
