# Generated by Django 3.1.4 on 2022-11-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20221119_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countInStoc',
            new_name='countInStock',
        ),
    ]
