# Generated by Django 3.1.4 on 2023-05-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20221121_0007'),
        ('base', '0011_auto_20221121_0156'),
    ]

    operations = [
    ]
